language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage erase
  - coverage run --source=authors/apps manage.py test
  - coverage report -m
  - coveralls
after_success:
  - coveralls

? deploy
provider: heroku
app: ah-magnificent6-staging
run:
  - "python manage.py makemigrations"
  - "python manage.py migrate"
