language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
services:
  - postgresql
before_script:
  - psql -c "CREATE ROLE authorsHaven WITH SUPERUSER LOGIN PASSWORD 'authorshaven';" -U postgres
  - psql -c "CREATE DATABASE testAuthorsHaven;" -U postgres
  - export DJANGO_SETTINGS_MODULE=authors.settings
script:
  - coverage erase
  - coverage run --source='.' manage.py test
  - coverage report -m
after_success:
  - coveralls
