language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE testAuthorsHaven;" -U postgres
script:
  - coverage erase
  - coverage run --source='.' manage.py test
  - coverage report -m
  - coveralls
after_success:
  - coveralls
