language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE testAuthorsHaven;" -U postgres
env:
  global:
    - "DJANGO_SETTINGS_MODULE=authors.settings"
    - SECRET_KEY=secretkey
    - "DATABASE_URL=psql://postgres:postgres@127.0.0.1:5432/testAuthorsHaven"
script:
  - coverage erase
  - coverage run --source='.' manage.py test
  - coverage report -m
  - coveralls
after_success:
  - coveralls
