language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE authorsHaven WITH SUPERUSER LOGIN PASSWORD 'authorshaven';" -U postgres
  - psql -c "CREATE DATABASE testAuthorsHaven;" -U postgres

script:
  - coverage erase
  - coverage run --source='.' manage.py test
  - coverage report -m

after_success:
  - coveralls
