# Generated by Django 2.1 on 2018-09-24 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=9876, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='favourited',
            field=models.ManyToManyField(blank=True, related_name='favourited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='userDisLikes',
            field=models.ManyToManyField(blank=True, related_name='_article_userDisLikes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='userLikes',
            field=models.ManyToManyField(blank=True, related_name='_article_userLikes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerating',
            name='article',
            field=models.ForeignKey(default=6789, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlerating',
            name='user',
            field=models.ForeignKey(default=4352, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(default=6543211, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('article', 'user')},
        ),
    ]
