# Generated by Django 2.1 on 2018-09-11 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='favoritesCount',
        ),
        migrations.RemoveField(
            model_name='article',
            name='favorited',
        ),
        migrations.AddField(
            model_name='article',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited', to=settings.AUTH_USER_MODEL),
        ),
    ]
