# Generated by Django 2.1 on 2018-09-12 11:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20180912_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlerating',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlerating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='articlerating',
            unique_together={('article', 'user')},
        ),
    ]
