# Generated by Django 2.1 on 2018-09-12 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20180912_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('article', 'user')},
        ),
    ]
