# Generated by Django 2.1 on 2018-09-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180911_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='favorited',
            new_name='favourited',
        ),
    ]
