# Generated by Django 2.1 on 2018-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180912_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
