# Generated by Django 2.1 on 2018-09-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180921_1024'),
        ('articles', '0003_auto_20180921_0956'),
    ]

    operations = [
    ]
