# Generated by Django 2.1 on 2018-09-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180912_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlerating',
            unique_together=set(),
        ),
    ]
