# Generated by Django 2.1 on 2018-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='DislikesCount',
            field=models.IntegerField(default=0),
        ),
    ]
