# Generated by Django 2.1 on 2018-10-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180925_1223'),
        ('articles', '0004_auto_20180929_1335'),
    ]

    operations = [
    ]
