# Generated by Django 2.1 on 2018-09-13 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20180913_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='favorited',
        ),
        migrations.AddField(
            model_name='article',
            name='favourited',
            field=models.ManyToManyField(blank=True, related_name='favourited', to=settings.AUTH_USER_MODEL),
        ),
    ]
