# Generated by Django 2.1 on 2018-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180916_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='userDisLikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='userLikes',
        ),
        migrations.AddField(
            model_name='article',
            name='DislikesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
