# Generated by Django 2.1 on 2018-09-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180913_1427'),
        ('articles', '0005_article_dislikescount'),
    ]

    operations = [
    ]
