# Generated by Django 2.1 on 2018-09-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180912_1603'),
        ('articles', '0005_auto_20180913_1427'),
    ]

    operations = [
    ]
