# Generated by Django 2.1 on 2018-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articlereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
