# Generated by Django 2.1 on 2018-09-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comment_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commented_by',
        ),
    ]
