# Generated by Django 2.1 on 2018-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180918_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='_article_tags_+', to='articles.ArticleTags'),
        ),
    ]
