# Generated by Django 2.1 on 2018-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180918_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletags',
            name='tag_name',
            field=models.CharField(blank=True, default='No tag', max_length=20, unique=True),
        ),
    ]
