# Generated by Django 2.1 on 2018-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180918_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletags',
            name='tag_name',
        ),
        migrations.RemoveField(
            model_name='articletags',
            name='tags',
        ),
        migrations.AddField(
            model_name='articletags',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articletags',
            name='tag',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
