# Generated by Django 2.1 on 2018-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletags',
            name='articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='articles.ArticleTags'),
        ),
    ]
