# Generated by Django 2.1 on 2018-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20180918_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(blank=True, null=True, to='articles.ArticleTags'),
        ),
    ]
